using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LaundryManager.Views
{
    public partial class UCCreateBill : DevExpress.XtraEditors.XtraUserControl
    {
        public UCCreateBill()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnCreateBill_Click(object sender, EventArgs e)
        {
            this.Parent.Controls.Remove(this);
        }

        private void UCCreateBill_Load(object sender, EventArgs e)
        {

        }
    }
}
