using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LaundryManager.Views
{
    public partial class UCServicePriceList : DevExpress.XtraEditors.XtraUserControl
    {
        public UCServicePriceList()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            fAddService addService = new fAddService();
            addService.ShowDialog();
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            this.Parent.Controls.Remove(this);
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            int rowIndex = gvServices.FocusedRowHandle;
            string colFieldName = "ID";
            object value = gvServices.GetRowCellValue(rowIndex, colFieldName);

            string serviceID = (string)value;
            if (value != null)
            {
                DialogResult _dialog = MessageBox.Show("Bạn có muốn xoá dịch vụ này không? ", "Thông báo!", MessageBoxButtons.YesNoCancel);
                if (_dialog == System.Windows.Forms.DialogResult.Yes)
                {
                    try
                    {
                        _ = Controllers.ServiceController.DeleteService(serviceID);
                        XtraMessageBox.Show("Xoá thành công!");
                    }
                    catch
                    {
                        XtraMessageBox.Show("Loi");
                    }
                }            
            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng xoá", "Cảnh báo", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }
    }
}
