using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LaundryManager.Views
{
    public partial class UCServicePriceList : DevExpress.XtraEditors.XtraUserControl
    {
        public UCServicePriceList()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            fAddService addService = new fAddService();
            addService.ShowDialog();
            sqlDataSource1.FillAsync();
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            this.Parent.Controls.Remove(this);
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            int rowIndex = gvServices.FocusedRowHandle;
            string colFieldName = "ID";
            object value = gvServices.GetRowCellValue(rowIndex, colFieldName);

            string serviceID = (string)value;
            if (value != null)
            {
                DialogResult _dialog = MessageBox.Show("Bạn có muốn xoá dịch vụ này không? ", "Thông báo!", MessageBoxButtons.YesNoCancel);
                if (_dialog == System.Windows.Forms.DialogResult.Yes)
                {
                    try
                    {
                        _ = Controllers.ServiceController.DeleteService(serviceID);
                        XtraMessageBox.Show("Xoá thành công!");
                        // SELECT Services.ID, ServiceName, Unt.Unit, Price, Services.Note FROM dbo.Services LEFT JOIN dbo.Units Unt ON Unt.ID = Services.UnitID
                        sqlDataSource1.FillAsync();
                    }
                    catch
                    {
                        XtraMessageBox.Show("Loi");
                    }
                }            
            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng xoá", "Cảnh báo", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void btnEdit_Click_1(object sender, EventArgs e)
        {
            object value;

            // Lay ID
            int rowIndex = gvServices.FocusedRowHandle;
            string colFieldID = "ID";
            value = gvServices.GetRowCellValue(rowIndex, colFieldID);

            string serviceID = (string)value;
            // Lay serviceName
            string colFieldName = "ServiceName";
            value = gvServices.GetRowCellValue(rowIndex, colFieldName);
            string serviceName = (string)value;

            // Lay Unit
            string colFieldUnitID = "UnitID";
            value = gvServices.GetRowCellValue(rowIndex, colFieldUnitID);
            string unitID = (string)value;

            // Lấy đơn giá
            string colFieldPrice = "Price";
            value = gvServices.GetRowCellValue(rowIndex, colFieldPrice);
            string price = value.ToString();

            // Lấy Mô tả
            string colFieldNote = "Note";
            value = gvServices.GetRowCellValue(rowIndex, colFieldNote);
            string note = (string)value;

            fEditService editService = new fEditService(serviceID, serviceName, unitID, price, note);
            editService.ShowDialog();
            sqlDataSource1.FillAsync();
        }
    }
}
