USE DATABASE_QUANLYTIEMGIATUI
GO

-- TỰ ĐỘNG TẠO ID DỊCH VỤ

CREATE FUNCTION fcgetServiceID()
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @Idx INT = 1
	DECLARE @ServiceID VARCHAR(15) = 'DV0000001'

	WHILE EXISTS ( SELECT ID FROM Services WHERE ID = @ServiceID)
	BEGIN
		SET @Idx = @Idx + 1
		SET @ServiceID = 'DV' + REPLICATE('0', 7 - LEN(CAST(@Idx AS VARCHAR))) + CAST(@Idx AS VARCHAR)
	END
	
	RETURN CONVERT(VARCHAR(10), @ServiceID)

END
GO


-- TỰ ĐỘNG TẠO ID ĐƠN VỊ TÍNH
CREATE FUNCTION fcgetUnitID()
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @Idx INT = 1
	DECLARE @UnitID VARCHAR(15) = 'DVT000001'

	WHILE EXISTS ( SELECT ID FROM Units WHERE ID = @UnitID)
	BEGIN
		SET @Idx = @Idx + 1
		SET @UnitID = 'DVT' + REPLICATE('0', 6 - LEN(CAST(@Idx AS VARCHAR))) + CAST(@Idx AS VARCHAR)
	END
	
	RETURN CONVERT(VARCHAR(10), @UnitID)
END
GO


-- TỰ ĐỘNG TẠO BILLCODE
ALTER FUNCTION fcgetBillCode()
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @Idx INT = 1
	DECLARE @BillCode VARCHAR(15) = 'CN00.0001'

	WHILE EXISTS ( SELECT BillCode FROM dbo.Bills WHERE BillCode = @BillCode)
	BEGIN
		SET @Idx = @Idx + 1
		SET @BillCode = 'CN00.' + REPLICATE('0', 4 - LEN(CAST(@Idx AS VARCHAR))) + CAST(@Idx AS VARCHAR)
	END
	
	RETURN CONVERT(VARCHAR(10), @BillCode)

END
GO
